### ISSUE TITLE
Switch the master branch to 'gh-pages'

### ISSUE THREAD

**Issue by mikedillion** [maptimelex/d3-mapping#4]
Then everything merged will be available on github.io immediately like: http://maptimelex.github.io/d3-mapping/d3-map02-interaction/index.html

![screen shot 2015-06-25 at 6 09 29 pm](https://cloud.githubusercontent.com/assets/76214/8366725/5c73ca58-1b65-11e5-90e5-bf43fdc4c077.png)

**Comment by rgdonohue** [comment]
Makes sense to me! Is it as easy as just switching it in that dropdown? Go ahead?

**Comment by maptastik** [comment]
:+1:

**Comment by mikedillion** [comment]
Done!
